# Generated by Django 5.2.8 on 2025-11-21 14:27

import django.db.models.deletion
import payments.utils.references
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_code', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('customer_code', models.PositiveIntegerField(unique=True)),
                ('contact_email', models.EmailField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='payments.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='payments.customer'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_account_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], max_length=3)),
                ('payment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Processed', 'Processed'), ('Failed', 'Failed'), ('In Progress', 'In Progress')], default='In Progress', max_length=11)),
                ('is_batch', models.BooleanField(default=False)),
                ('reference', models.CharField(default=payments.utils.references.generate_payment_reference, editable=False, max_length=30, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.account')),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('iban__gt', ''), ('iban__isnull', False)), models.Q(('account_number__gt', ''), ('account_number__isnull', False)), _connector='OR'), name='iban_or_account_required'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'display_name'), name='unique_account_per_company'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='unique_company_per_customer'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['currency'], name='payments_pa_currenc_b1f04b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account', 'payment_date'], name='payments_pa_account_713bbf_idx'),
        ),
    ]
