# Generated by Django 5.2.8 on 2025-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='beneficiary_iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('beneficiary_iban__gt', ''), ('beneficiary_iban__isnull', False)), models.Q(('beneficiary_account_number__gt', ''), ('beneficiary_account_number__isnull', False)), _connector='OR'), name='beneficiary_iban_or_account_required'),
        ),
    ]
